update to 1.16
BuiltBrokenModding/SBM-woodenShears pull request #12
Opened 2020-07-21 07:20 UTC by LegendaryGeek

2020-07-21 09:22 UTC, bl4ckscor3 requested changes
1. Please remove `CREDITS.txt`, `LICENSE.txt`, `README.txt`, and `changelog.txt`. Those are Forge-specific files and have nothing to do with this project. We also already have all of those files (changelog is in the readme) specific to our project.
2. The game doesn't start with this mod installed. Either you didn't test your changes (which you should have done) or you did not commit the changes to `mods.toml`.

2020-07-21 09:22 UTC, bl4ckscor3 commented on src/main/java/com/builtbroken/woodenshears/loot/LootModifierWoodenShears.java
> +
Unnecessary new lines

2020-07-21 09:22 UTC, bl4ckscor3 commented on src/main/java/com/builtbroken/woodenshears/loot/LootModifierWoodenShearsSerializer.java
> +
Unnecessary new lines

2020-07-22 14:20 UTC, LegendaryGeek commented
should be fixed now

2020-07-22 15:02 UTC, bl4ckscor3 commented
Still got an extra empty line at each place where you removed one (I marked two lines in both my comments because there are two lines to remove each!) Also since you've change the loader version dependency, might as well change the forge dependecy to `[32,)` as well. Code looks good otherwise, will test soon.

2020-07-30 19:01 UTC, merged